version: "3.8"

services:
  weight-backend:
    build: .
    ports:
      - "8085:5000"  # Expose port only for production
    depends_on:
      - weight-db
    env_file: 
      - .env.${ENV}  # Use environment-specific .env file
    networks:
      - ${NETWORK_NAME}  # Network based on environment
    restart: always  

  weight-db:
    image: mysql:9.0.1
    ports:
      - "3333:3306"  # Expose port only for production
    volumes:
      - /Users/ayala/Downloads/dev/gan-shmuel/weight/db/weightdb.sql:/docker-entrypoint-initdb.d/billingdb.sql  # Only needed in test
    environment:
      MYSQL_ROOT_PASSWORD: ${BILLING_MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${BILLING_MYSQL_DATABASE_DB}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - ${NETWORK_NAME}  # Network based on environment

networks:
  test-network:
    driver: bridge
  prod-network:
    driver: bridge
