services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8090:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/ayala/Downloads/dev/gan-shmuel:/app/gan-shmuel
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]  
      interval: 30s  
      retries: 3      
      start_period: 10s  
      timeout: 5s 
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme  
      - SPLUNK_HTTP_EVENT_COLLECTOR=1 
      - SPLUNK_HEC_TOKEN=your_hec_token  
    ports:
      - "8088:8088"  # Splunk HTTP Event Collector (HEC) port
      - "8000:8086"  # Splunk Web UI port
      - "9997:9997"  # Splunk Forwarding port (for forwarders)
    volumes:
      - splunk-data:/opt/splunk/var
    networks:
      - dev-network
    restart: always
networks:
  dev-network:
    driver: bridge
