services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   splunk:
    #     condition: service_healthy
    privileged: true
    ports:
      - "8090:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/dev/gan-shmuel:/app/gan-shmuel
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "splunk"
      options:
        splunk-token: "9420d629-935e-46b7-8c65-73aef6ee6e6d"
        splunk-url: "http://splunk:8088"
        splunk-verify-connection: "false"
        splunk-format: "raw"
        splunk-index: "main"
        splunk-source: "ci-service"
        splunk-sourcetype: "docker"

networks:
  dev-network:
    name: dev-network
    driver: bridge

volumes:
  splunk-data:
    driver: local