services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_HTTP_EVENT_COLLECTOR=1
      - SPLUNK_HEC_TOKEN=your_hec_token
      - SPLUNK_HEC_ENABLE=1  
      - SPLUNK_HEC_SSL=false 
      - SPLUNK_HEC_PORT=8088 
    ports:
      - "8088:8088"
      - "8086:8000"
      - "9997:9997"
    volumes:
      - splunk-data:/opt/splunk/var
      - /app/splunk-config:/opt/splunk/etc
    networks:
      - dev-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/en-US/account/login"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s

networks:
  dev-network:
    name: dev-network
    driver: bridge

volumes:
  splunk-data:
    driver: local
