services:
  # Billing Backend Service
  billing-backend:
    container_name: ${BILLING_BACKEND_NAME:-billing-backend}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BILLING_BACKEND_PORT:-8085}:5000" 
    depends_on:
      - billing-db
    env_file:
      - .env.${ENV} 
    networks:
      - ${NETWORK_NAME:-test-network}  
    restart: always
    logging:
      driver: "splunk"
      options:
        splunk-token: "f304dc24-869b-4907-a3bf-6d47f9f8d1bf"
        splunk-url: "http://splunk:8088"
        splunk-verify-connection: "false"
        splunk-format: "raw"
        splunk-index: "main"
        splunk-source: "billing"
        splunk-sourcetype: "docker"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
  # Billing Database Service
  billing-db:
    image: mysql:9.0.1
    container_name: ${BILLING_DB_NAME:-billing-db}
    ports:
      - "${BILLING_DB_PORT:-3307}:3306"  
    volumes:
      - ./database/billingdb.sql:/docker-entrypoint-initdb.d/billingdb.sql  
      - billing-db-data:/var/lib/mysql 
      - /app/.env.test:/app/.env.test
      - /app/.env.prod:/app/.env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${BILLING_MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: billdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - ${NETWORK_NAME:-test-network}  

networks:
  test-network:
    driver: bridge
  prod-network:
    driver: bridge

volumes:
  billing-db-data:
    driver: local
