services:
  # Weight Backend Service
  weight-backend:
    container_name: ${WEIGHT_BACKEND_NAME:-weight-backend}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEIGHT_BACKEND_PORT:-8080}:5000"  
    depends_on:
      - weight-db
    env_file:
      - .env.${ENV} 
    networks:
      - ${NETWORK_NAME:-test-network}  
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  # Weight Database Service
  weight-db:
    image: mysql:9.0.1
    container_name: ${WEIGHT_DB_NAME:-weight-db}
    ports:
      - "${WEIGHT_DB_PORT:-3306}:3306" 
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql  
      - weight-db-data:/var/lib/mysql 
      - /app/.env.test:/app/.env.test
      - /app/.env.prod:/app/.env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${WEIGHT_MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: weight
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - ${NETWORK_NAME:-test-network}  

networks:
  test-network:
    driver: bridge
  prod-network:
    driver: bridge

volumes:
  weight-db-data:
    driver: local